service: puppeteer-scraper

provider:
  environment:
    ENV: ${self:provider.stage}
  name: aws
  region: us-west-2
  runtime: nodejs20.x
  stage: ${opt:stage, "dev"}

functions:
  scraper:
    memorySize: 512
    timeout: 300
    image:
      uri: 654654573394.dkr.ecr.us-west-2.amazonaws.com/technokrax-news-scraper:latest
      command:
        - dist/index.handler